stages:
  - stage: Import
    displayName: 'Import'
    jobs:
      - job: ImportJob
        pool: 
          vmImage: windows-2022
        displayName: 'Import'
        steps:
        - checkout: self
          fetchDepth: 1
          displayName: 'Checkout Source Code'
          path: self          

        - checkout: ALM4Dataverse
          fetchDepth: 1
          displayName: 'Checkout ALM Templates Repository'
          path: alm

        - task: PowerPlatformToolInstaller@2
          displayName: 'Install Power Platform Tools'
          inputs:
            AddToolsToPath: true

        - task: ALM4Dataverse.alm4dataverse-azdo-extensions.alm4dataverse-set-connection-variables.ALM4DataverseSetConnectionVariables@1
          displayName: 'Set Connection Variables'
          name: ALM4DataverseSetConnectionVariables
          inputs:
            authenticationType: 'PowerPlatformSPN'
            PowerPlatformSPN: Dev-${{ variables['Build.SourceBranchName'] }}

        - pwsh: |
            & "$(Pipeline.Workspace)/alm/pipelines/scripts/installdependencies.ps1"
            & "$(Pipeline.Workspace)/alm/pipelines/scripts/connect.ps1" -Url $(ALM4DataverseSetConnectionVariables.EnvironmentUrl)
            & "$(Pipeline.Workspace)/alm/pipelines/scripts/import.ps1" `
              -SourceDirectory "$(Pipeline.Workspace)/self" `
              -ArtifactStagingDirectory "$(Build.ArtifactStagingDirectory)"
          displayName: 'Connect and Import Solutions'
          workingDirectory: '$(Pipeline.Workspace)/self'    
          env:
            AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)      
