trigger: none # Run manually when you want to import changes from source control

name: Import to Dev-${{ variables['Build.SourceBranchName'] }}

resources:
  repositories:
    - repository: ALM4Dataverse
      type: git
      name: ALM4Dataverse

variables:
- group: Environment-Dev-${{ variables['Build.SourceBranchName'] }}

parameters:
- name: useAlm4DataverseExtension
  type: boolean
  default: true

stages:
- template: pipelines/templates/import.yml@ALM4Dataverse
  parameters:
    useAlm4DataverseExtension: ${{ parameters.useAlm4DataverseExtension }}
    environmentUrl: $(EnvironmentUrl)
